### ISSUE TITLE
Quick start code does not compile

### ISSUE THREAD

**Issue by space-alien** [Sergio0694/ComputeSharp#106]
.NET 5 console app with just the ComputeSharp 2.0.0-alpha.1 package added.

Minimal repro:

```cs
namespace ComputeSharp1
{
    [AutoConstructor]
    public readonly struct MultiplyByTwo : IComputeShader
    {
        public readonly ReadWriteBuffer<float> buffer;

        public void Execute()
        {
            buffer[ThreadIds.X] *= 2;
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            // Get some sample data
            int[] array = Enumerable.Range(0, 100).ToArray();

            // Allocate a GPU buffer and copy the data to it.
            // We want the shader to modify the items in-place, so we
            // can allocate a single read-write buffer to work on.
            using ReadWriteBuffer<float> buffer = Gpu.Default.AllocateReadWriteBuffer(array);
        }
    }
}
```

First issue
`using ReadWriteBuffer<float> buffer = Gpu.Default.AllocateReadWriteBuffer(array);` reports a type mismatch. This is fixed with `using ReadWriteBuffer<int> buffer` instead.

Second issue
Build now fails with the error: `The namespace 'ComputeSharp1' already contains a definition for 'Program'`. I tried removing the namespace altogether - just in case - but that led to some more ComputeSharp errors.

All traced back to the `[AutoConstructor]` - removing it would allow the build just fine.

**Comment by space-alien** [comment]
Ah, third issue.. :)

```cs
// Launch the shader
Gpu.Default.For(buffer.Length, new MyShader(buffer));   <-- what's supposed to be here?

// Get the data back
buffer.CopyTo(array);
```

**Comment by Sergio0694** [comment]
Hey, thanks for the report!
You're absolutely right, I made a few typos in that sample, whoops! 😅
Was writing them directly in VS Code and changing them often as I kept working on the library, so a few mistakes slipped through.

Specifically, with respect to the three issues you mentioned:

1. That sample should be using `int` in the buffer type, as that's the type of the source array as well
2. That build error is because I forgot a `partial` in the shader type declaration, so the source generator is trying to declare the constructor in a type with the same name that is not recognized as being actually the same, hence that conflict and failure
3. That's a leftover from a previous version of the docs, that shader should definitely be `MultiplyByTwo` there, yeah 😄

Thanks again!
