### ISSUE TITLE
Globals not working

### ISSUE THREAD

**Issue by HaileyStorm** [Sergio0694/ComputeSharp#117]
Any globals I try to define cause compile error. I have tried e.g. "private static int _seed" and I get:

Error	CS0122	'MainWindow.Process._seed' is inaccessible due to its protection level	Ants	C:\Users\Hailey\Google Drive\Programming\Ants\Ants\ComputeSharp.SourceGenerators\ComputeSharp.SourceGenerators.IComputeShaderDataLoaderGenerator\[ComputeSharp]_[IComputeShaderDataLoaderGenerator]_[Ants.MainWindow.Process].cs	19	Active

If I try "public static int _seed" I get:

Error	CS0176	Member 'MainWindow.Process._seed' cannot be accessed with an instance reference; qualify it with a type name instead	Ants	C:\Users\Hailey\Google Drive\Programming\Ants\Ants\ComputeSharp.SourceGenerators\ComputeSharp.SourceGenerators.IComputeShaderDataLoaderGenerator\[ComputeSharp]_[IComputeShaderDataLoaderGenerator]_[Ants.MainWindow.Process].cs	19	Active

I am running VS 16.10.0 Preview 1.0. I have tried .NET 5 and .NET 6. I've tried without installing Microsoft.Toolkit.Diagnostics and letting it grab it automatically / use what's built-in, and I've tried installing v7.0.1.

I've attached my solution.

Thank you!

[Ants.zip](https://github.com/Sergio0694/ComputeSharp/files/6247216/Ants.zip)

**Comment by Sergio0694** [comment]
Hey @HaileyStorm, thank you for the bug report and for trying out the library! 🙌

So, there's a couple things coming into play here:
- The reason why static fields aren't working is because the current version on NuGet is not really up to par with what's on `main` (I only push a new NuGet package every now and then, so stuff that's been recently added here and visible in the readme might not be actually available from that public package just yet), and in particular static fields to represent shader globals are one of them. You can get them to work by using a local preview package from the CI though: go to the "Actions" tab in the repo and then click on the most recent passing ✅ run from the `main` branch. Scroll down to artifacts and download zip, then extract the `.nupkg` package from that zipped file. Then copy that to a folder of your choice and add that as a custom package source for your solution, and add a reference to that preview version in your project 🙂

<a href="https://github.com/Sergio0694/ComputeSharp/actions/"><img src="https://user-images.githubusercontent.com/10199417/113409406-7e285900-93b1-11eb-8226-4e8c63f19bfb.png" alt="GitHub Actions" /></a>

- Not entirely sure why the `[AutoConstructor]` attribute didn't work properly in your solution, when I tried. Looking at the generated files, the constructor was created correctly, yet the solution failed to build. I removed the attribute and manually added the constructor and that fixed it, I'll investigate this.
- There's a shader compilation error due to the `Cycle` method being referenced by a method declared above it, as currently I'm not ordering methods in a shader based on precedence (I'll add on my TODO list). For now, an easy workaround is to just swap `Cycle` with `GetCurrentFloat`, so that it's declared above it in your shader.

With those two changes I managed to get your sample to build and run fine. Let me know if it works for you! 😄

**P.S.:** a couple other general suggestions on your code after looking at it. There's two things you might want to change.
- One is that `Task.Delay(speed).ContinueWith(t => RepeatLoop());` in `RepeatLoops`, which means that each `RepeatLoop` call will start repeating forever no matter who called it. This causes the button being pressed to also start another (separate) repeat loop than the one started when the whole window was loaded. You might want to make it so that if you press the button, the method is only called once instead, as it's already repeating in the background anyway.
- An optimization you might want to do later on is to avoid allocating a new texture every time `RepeatLoop` is called (you also forgot to dispose it!). What you can do instead is to keep a texture in a field, and just reuse that to avoid repeated allocations. In the future, for maximum performance, you might also want to keep an `UploadTexture2D<Bgra32>` and a `ReadBackTexture2D<Bgra32>` instance to work on, to avoid allocating temporary internal resources when copying data back and forth (though this is a more advanced thing and you can worry about it later). Hope this helps!

**Comment by HaileyStorm** [comment]
Thank you!!

With the updated package and the method-order swap, I have globals working, as well as the on-shader random number generator. I'll be sure to keep my package up to date!

Thank you also for the allocation recommendations :) I'll be sure to implement them. I confess I don't understand exactly how the Upload/ReadBack buffers work, but I haven't spent any time on them yet. I'm sure I'll sort it out.

As for the RepeatLoop stuff, I'm sure you can tell that at the moment this project is just me messing around with things. The button is a leftover and will go away. Your point is definitely valid and I appreciate the extra effort calling out the issue.

One last thing, if it's appropriate for me to ask here: will Hlsl.Noise() be making a comeback at any point? Or is that a new HLSL version limitation?

This is a truly brilliant project and I very much appreciate all your efforts. Maybe at some point I'll get familiar enough to submit some pull reqs ;)

Thank you again!

**Comment by Sergio0694** [comment]
That's awesome, glad you got unblocked! Hope you'll have fun using the lib and that it'll work well for you! 😄

> "One last thing, if it's appropriate for me to ask here: will Hlsl.Noise() be making a comeback at any point? Or is that a new HLSL version limitation?"

Unfortunately the `noise` intrinsics was removed in Shader Model 2.0 ([see here](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-noise)), so it's just not supported anymore 😭
I agree that that seemed useful indeed, to be honest I'm sad it was deprecated as well. Not even sure why that was the case.

Thank you so much for the kind words! Really appreciate the support! 😊

**Comment by HaileyStorm** [comment]
Bummer indeed. Thanks again!
