### ISSUE TITLE
How do I pass a single float to a shader?

### ISSUE THREAD

**Issue by Kuwertzel** [Sergio0694/ComputeSharp#120]
First of all, thank you for this awesome repo! It makes working with GPU processing so much easier! ;)
Since I don't have a lot of experience with shaders overall (other than Unitys ComputeShaders) I ran into the following problem while trying to build a little particle simulation.

I have the following code:

Snippet of `ShaderHelper.cs`:
``` C#
public static void ParticlesUpdate(ref Particle[] particles, ref float deltaTime)
{
    // Create Buffers
    using ReadWriteBuffer<Particle> particlesBuffer = Gpu.Default.AllocateReadWriteBuffer(particles);
    using ReadWriteBuffer<float> deltaTimeBuffer = Gpu.Default.AllocateReadWriteBuffer<float>(deltaTime); // < Error 1

    // Launch shader
    Gpu.Default.For(particlesBuffer.Length, new Shaders.ParticleUpdate(particlesBuffer, deltaTimeBuffer)); // < Error 2

    // Get data back
    particlesBuffer.CopyTo(particles);
    deltaTimeBuffer.CopyTo(deltaTime); // < Error 3

}
```

Snippet of `CS_ParticleUpdate.cs`:
``` C#
[AutoConstructor]
public readonly partial struct ParticleUpdate : IComputeShader
{
    public readonly ReadWriteBuffer<Particle> particlesBuffer;
    public readonly float deltaTimeBuffer;

    public void Execute()
    {
        // Shader Code using particlesBuffer and deltaTimeBuffer here
    }
}
```

Passing the `particles` array buffer works fine, however trying to do the same for the float `deltaTime` gives me the following errors:
```
Argument 2: Cannot convert from 'float' to 'int'
Argument 2: Cannot convert from 'ComputeSharp.ReadWriteBuffer<float>' to 'float'
Argument 2: Cannot convert from 'float' to 'float[]'
```

I assume my mistake is that I can only pass arrays using a `ReadWriteBuffer` but how do I pass a single float to my shader?
Fyi: I'm making a particle simulation that behaves like a slime creature, hence the weird file names :)

Following is my full project. The files shown above are at `Helpers/ShaderHelper.cs` and `Shaders/CS_ParticleUpdate.cs`.
[03_Slime.zip](https://github.com/Sergio0694/ComputeSharp/files/6408670/03_Slime.zip)

**Comment by Sergio0694** [comment]
Hi, thanks for trying out ComputeSharp! 😄
The error you're seeing is to be expected, you're tryin to assign a buffer to a scalar field in your shader.
There are two ways to pass a `float` to/from a shader, depending on your needs:
- If you only use the value in the shader and don't need to return it after the shader has completed, you can just have a `float` field in your shader and set that when creating the shader. It will be copied on the GPU and you'll be able to use that.
- If you want to also return it after the shader has completed, you'll need to create a buffer with just that element, and then use that in the shader.

It seems you're trying to do this second option, but you have some errors in your code:
1. You're calling `AllocateReadWriteBuffer` and only passing a scalar. That API needs an array or a `Span<T>`. For instance, you could pass `new float[] { deltaTime }` instead, or a local `Span<float>` if you want to avoid allocations.
2. This second error is because the `deltaTimeBuffer` field in your shader is `float`. Change that to a buffer type.
3. This last error is because you're trying to read to a scalar. You need to copy the data back to an array/span, and then copy that first element there to your target `deltaTime` variable.

I'd recommend reading at the docs in the README, going through the samples and also reading the XML docs over the various APIs, there should be plenty on info that might help there as well 🙂

**P.S.**: bonus point, I couldn't help but notice your `ClearPixels` method in the `Slime.Helper.Shader` class, which is completely inefficient. You're essentially just clearing a target array, but you're takaing an extremely slow and convoluted approach:
- You have a `byte[]` array to clear
- You're using `Array.ConvertAll` to create a `uint[]` array with the same values (super slow and also creates an extra array)
- Then you're allocating a GPU buffer
- You're copying the `uint[]` array to it (this also allocates a temporary GPU transfer buffer)
- You then run a shader that just does `buffer[ThreadIds.X] = 0`
- You then copy the buffer back from the GPU (this also requires another temporary transfer buffer)
- You then use `Array.ConvertAll` again (slow!) to get a (new!) `byte[]` array from the `uint[]` array
- Finally, you return this array (even though you've already set it by `ref`)

All this is completely unnecessary, you can do the same (and **MUCH** faster) with just this:

```csharp
pixels.AsSpan().Clear();
```

No allocations, no copies, no shaders needed.
That's it 🥳

**Comment by Kuwertzel** [comment]
Thanks for your help 😃
Also thanks for the bonus. I now store the pixels array as `uint` in the first place so that I only need to convert it once per tick to pass it into the SFML texture method. Unfortunately, it only takes `byte[]`, which in reverse (afaik) can't be passed into the shader but it's enough to run the simulation fluently for now :)

**Comment by Sergio0694** [comment]
That's great to hear, really happy that ComputeSharp is working well for you! Feel free to open another issue should you have other problems in the future! 😄
