### ISSUE TITLE
Keep GPU Responsive?

### ISSUE THREAD

**Issue by S41L0R** [Sergio0694/ComputeSharp#132]
Hey, so for fun I'm making a hailstone (Aka the Collatz Conjecture) calculator. I'm having it run on the GPU, and the problem arises when I give it too many numbers to calculate. Upon running, my screen freezes for a moment, then Visual Studio tells me the following:

`'The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.'`

What this tells me is that the GPU is spending too much of it's time working on my program, and not enough time drawing actual frames for Windows. Windows notices this, and suspends the GPU, causing the crash. I'd like to know: Is there a way I can limit how much of my GPU's resources are used? Preferably in a way that adapts to the power of different GPUs.

**Comment by Sergio0694** [comment]
There's not really a way to dynamically scale workloads like that in an automatic way. You should generally avoid to have shaders that can take too long to run even on a low end device. If you have a to process a lot of data or have shaders which are expensive, consider using a `ComputeContext` and enqueue multiple dispatches, each working on a smaller section of the data. That is, the issue is not the GPU taking too long to process the data per se, but rather it doing all that work in a single dispatch. This is problematic because it means nothing else can interleave that work on the GPU, including Windows, which is why shaders have a hard cap that if you exceed, cause the device to be removed. I'd recommend trying this "tiled" approach to work around this. To make a simple example, to illustrate the general idea:

```csharp
// Instead of this
device.For(1000, new MyShader(buffer));

// Do something like this
using (var context = device.CreateComputeContext())
{
    for (int i = 0; i < 10; i++)
    {
        context.For(100, new MyShader(buffer, i * 100));
    }
}
```

And then adjust the offset into the shader to know which "tile" you're processing. This example is just to give the overall idea, of course make sure to properly tile your data in whatever way works best for you, and to pick the most appropriate tile size depending on what kind of shaders you're running exacly.

**Comment by rickbrew** [comment]
It's possible to disable GPU timeout detection via https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_command_queue_flags

In general it's better to subdivide your work so each unit of execution can complete in less than 2 seconds. But, if you're in a jam -- like if you need to get some kind of work job done _today_ -- you could probably fork ComputeSharp and use this flag to let things execute without the timeout suspension thing. It's still possible Windows could suspend your GPU work anyway, the flag is more of a request/hint/recommendation, but I've seen it work well in a few cases.
