### ISSUE TITLE
More samples for custom structs

### ISSUE THREAD

**Issue by madsami** [Sergio0694/ComputeSharp#134]
I want to use this for a data computation experiment, not visualization, however I'm finding it difficult to understand how to navigate the interface with custom structs since the samples only use buffers of plain types. Are there any chances of having a sample added?
Best-

**Comment by Sergio0694** [comment]
Support for custom structs is still limited due to it being work in progress (eg. instance methods and constructors aren't supported just yet, though they're planned), but there are some samples already showcasing them, in the `ImageProcessing` project 😄

There's a couple shaders using the custom `Complex` type:

https://github.com/Sergio0694/ComputeSharp/blob/d935bc1a09b8c62c1b8107f02316869073473e9e/samples/ComputeSharp.ImageProcessing/Processors/HlslBokehBlurProcessor%7BTPixel%7D.cs#L303-L334

Let me know if this helps and if you have other questions!

**Comment by Sergio0694** [comment]
Closing this, as OP didn't reply and the question seems to have been answered already anyway.
