### ISSUE TITLE
Float2, Float3, Float4 math operations not working

### ISSUE THREAD

**Issue by Patan77** [Sergio0694/ComputeSharp#149]
### Description
I'm not sure if **Float2**, **Float3**, **Float4** is suppose to be used only inside of the shader code or if its should be ok to use it in the rest of the C# code, because its possible to use it, it wont give an error, but simple math operation like + - / * will result in 0. 

I would assume it should behave the same way as System.Numerics Vector?

**Example console code:** 
```
Vector2 vec = new Vector2(1, 2);
vec = vec + vec; // = <2,4>

Float2 myFloat = new Float2(1, 2);
myFloat = myFloat + myFloat; // = <0,0>

Console.WriteLine(vec); 
Console.WriteLine(myFloat);

vec = new Vector2(1, 2);
vec = vec * vec; // = <1,4>

myFloat = new Float2(1, 2);
myFloat = myFloat * myFloat; // = <0,0>

Console.WriteLine(vec);
Console.WriteLine(myFloat);

float scale = 2;
vec = new Vector2(1, 2);
vec = vec * scale; // = <2,4>

myFloat = new Float2(1, 2);
myFloat = myFloat * scale; // = <0,0>

Console.WriteLine(vec);
Console.WriteLine(myFloat);
```
.

**Comment by Sergio0694** [comment]
This is actually by design: none of the HLSL types are supposed to be used to perform computations on the CPU.
You can see all the operators they define just don't do anything and simply return `0`:

https://github.com/Sergio0694/ComputeSharp/blob/539c6d49a463d3e06263a15dff0af696b377e12b/src/ComputeSharp/Core/Primitives/Float/Float3.g.cs#L1526

https://github.com/Sergio0694/ComputeSharp/blob/539c6d49a463d3e06263a15dff0af696b377e12b/src/ComputeSharp/Core/Primitives/Float/Float3.g.cs#L1534

https://github.com/Sergio0694/ComputeSharp/blob/539c6d49a463d3e06263a15dff0af696b377e12b/src/ComputeSharp/Core/Primitives/Float/Float3.g.cs#L1542

https://github.com/Sergio0694/ComputeSharp/blob/539c6d49a463d3e06263a15dff0af696b377e12b/src/ComputeSharp/Core/Primitives/Float/Float3.g.cs#L1550

These will instead all work correctly in a shader. The reason these methods return `0` and don't throw an exception is so that it's possible to use them in static constructors for shaders (ie. to initialize `static readonly` fields in a shader), which would otherwise crash as well if these methods threw an exception. If you need to perform operations on eg. `Float3` values on the CPU, simply convert them to `Vector3` and use that instead. I might add more helpers for this in the future as well 😄

What scenario were you trying to use this in specifically?
If you needed to use this in your code, maybe I can help suggest how to update that to make it work 🙂

**Comment by Avid29** [comment]
@Patan77 In my experience with the library, I choose to just use the ``System.Numerics`` Vectors because they're converted to hlsl code in the same way regardless.
