### ISSUE TITLE
common algorithms build in

### ISSUE THREAD

**Issue by ImmaB** [Sergio0694/ComputeSharp#210]
ComputeSharp could have some parallel algorithms implemented like prefix sum or sorting.
They are quite difficult to implement on your own, especially with optimized performance.

**Comment by Sergio0694** [comment]
This is not something I plan on adding to the library. It's non trivial work (eg. I'm not personally familiar with any of those algorithms), and the library itself is more geared towards providing basic building blocks for others to create things on top of, rather than having primitives such as these built-in. Others are welcome to create extension libraries though 😊

Thank you!
