### ISSUE TITLE
Problem with EmbeddedBytecode HLSL generation

### ISSUE THREAD

**Issue by mattiascibien** [Sergio0694/ComputeSharp#211]
### Description (optional)

When building a class with `[EmbeddedBytecode(3, 1, 1)]` I still get a shader source with a group size of 1.

### Reproduction Steps

```csharp
namespace ComputeSharpTest;

[AutoConstructor]
[EmbeddedBytecode(3, 1, 1)]
public readonly partial struct ParticleMovement : IComputeShader
{
    private readonly ReadWriteBuffer<Vector2> Positions;

    private readonly ReadOnlyBuffer<Vector2> Directions;

    public void Execute()
    {
        var threadId = ThreadIds.X;
        Positions[threadId] += Directions[threadId];
    }
}
```
Generates the following shader code

```hlsl
// ================================================
//                  AUTO GENERATED
// ================================================
// This shader was created by ComputeSharp.
// See: https://github.com/Sergio0694/ComputeSharp.

#define __GroupSize__get_X 1
#define __GroupSize__get_Y 1
#define __GroupSize__get_Z 1

cbuffer _ : register(b0)
{
    uint __x;
    uint __y;
    uint __z;
}

RWStructuredBuffer<float2> Positions : register(u0);

StructuredBuffer<float2> Directions : register(t0);

[NumThreads(__GroupSize__get_X, __GroupSize__get_Y, __GroupSize__get_Z)]
void Execute(uint3 ThreadIds : SV_DispatchThreadID)
{
    if (ThreadIds.x < __x && ThreadIds.y < __y && ThreadIds.z < __z)
    {
        int threadId = ThreadIds.x;
        Positions[threadId] += Directions[threadId];
    }
}

```

### Expected Behavior

`#define __GroupSize__get_X` should be 3

### Actual Behavior

`#define __GroupSize__get_X` is 1

### System info

This section should contain useful info such as:
- **ComputeSharp** 2.0.0-alpha18
- Windows 11 Build 22000.469
- Nvidia GeForce RTX 3060 
- .Net 6.0

**Comment by Sergio0694** [comment]
Hi @mattiascibien! I think there might be a misunderstanding here. How are you retrieving that HLSL code? If you're using `ReflectionServices`, that will _always_ just return 1, as documented in the docs, but it's not a representation of the actual shader:

https://github.com/Sergio0694/ComputeSharp/blob/c32e5b3f1a5eb515cc58383ab8a6fe53e84cec24/src/ComputeSharp.Dynamic/Shaders/Interop/ReflectionServices.cs#L29-L34

Additionally, I would strongly recommend _not_ using a thread size like `3`, as that'd be highly inefficient. The thread sizes should ideally be a multiple of the wavefront size of your GPU, and as a rule of thumb for a good value that works well across all GPUs (ie. nvidia, AMD, Intel, etc.), 64 is usually your best bet. So if you're using a shader that only dispatches along the X axis, you should use `(64, 1, 1)`. Or better yet, you should just use `DispatchAxis.X` instead of specifying the thread nums manually, and let ComputeSharp do the work for you 😊

**Comment by mattiascibien** [comment]
@Sergio0694 I forgot to check the docs (too much used to libs that do not have good docs). Thanks for the clarification and sorry for the issue.

**Comment by Sergio0694** [comment]
No worries, glad the issue is solved! 😊

Also just FYI, if you don't need to inspect the generated bytecode and you're only using precompiled shaders, you can avoid referencing `ComputeSharp.Dynamic` and only use `ComputeSharp`, which will save you ~20MB of native libs being bundled 👍
