### ISSUE TITLE
Add support for elements that generator skips over

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#250]
I find myself needing to add additional methods, properties, etc. to my shaders for the use of code _outside_ the shader. I've been encapsulating them in interfaces, but I suppose it could be generalized to any element

Right now I'm having to put static abstracts into my "infra interfaces", and then implement those static methods using explicit syntax. It's a bit clumsy but it does work thankfully thanks to my local fix for #242. However, I don't think this will scale well when/if I can expand this for use by plugin authors, because you have to do a lot of fixups to implement these interfaces, and really need a solid understanding of C# syntax for a fairly esoteric feature (fine for me, but it will reduce user-friendliness for others).

I can't currently think of a scenario for having the attribute on a method inside the shader (not from an implemented interface, I mean). So, feel free to add support for that but what I really need is the ability to tag an interface with this so the generator just ignores its methods and properties when compiling the shader, even without the explicit implementation syntax. (and I presume it would not let the shader use those methods or properties!)

As an example of what I'd like to be able to do:
```cs
[ComputeSharePlzIgnoreThisInterfaceInTheSourceGenerator]
interface IPixelShader<TPixelShader>
    : ID2D1PixelShader
      where TPixelShader : unmanaged, IPixelShader<TPixelShader>
{
    int InputCount { get; }
}

[D2DAttributesGoHere]
readonly partial struct MyShader 
    : IPixelShader<MyShader>
{
    // Automatically ignored because of the attribute on the interface
    public int InputCount => 1;

    public float4 Execute() { ... }
}
```

**Comment by Sergio0694** [comment]
After the work done in #252, I'm even more convinced this is not a good idea. This would require a new attribute and additional logic for the generator (as it'd have to then traverse the inteerface hierarchy to lookup that attribute for every single processed member), and it still would result in potentially confusing behavior anyway because properties that cause fields to be generated would still have to be blocked. I think the current approach is ok, where the generator allows explicitly implemented members as long as they're stateless. Additionally, I like the fact that the current design makes it obvious in the shader type itself what is or is not ignored for the shader, whereas here you would have no context to determine that by just looking at the shader type itself, as a property/method might actually be hidden just because it's actually implementing some interface member from an interface somewhere else that has this special attribute applied to it.

I can see the argument for making things simpler for plugin authors, but I'm not really convinced that's enough here. They would still have to understand what can and cannot be used in a shader, the only difference is on one case they'd have to understand how to write an explicit interface implementation, and on the other hand they'd have to learn about the attribute. So it's still a new thing to learn either way. Additionally, even with the attribute, explicit interface implementations would _also_ be skipped, so they could potentially use and have to learn both.

Closing this one 🙂
