### ISSUE TITLE
`D2D1PixelShaderEffect` should call `ID2D1RenderInfo::SetInstructionCountHint()`

### ISSUE THREAD

**Issue by rickbrew** [Sergio0694/ComputeSharp#277]
You've got this data in the `ShaderInfo`, so you can supply it to Direct2D.

Also probably be worth having `D2D1ReflectionServices.GetShaderInfo<TShader>()` cache the `ShaderInfo` object.

**Comment by Sergio0694** [comment]
So, there seem to be two different points here.

> "[instruction count] You've got this data in the `ShaderInfo`, so you can supply it to Direct2D."

I don't have access to this data from `ID2D1Effect`. That is only computed if you call `ReflectionServices`, which is expensive and does the actual reflection work to extract that data. If you just load an effect normally, that is not done, so that info is not there.

> "Also probably be worth having `D2D1ReflectionServices.GetShaderInfo<TShader>()` cache the `ShaderInfo` object."

I don't think we should cache that info in the library. If people wanted to cache that, they can just do that themselves. Additionally, you could compute that info with different shader profiles, which would affect the extracted data, so you'd have to cache them per-profile, which would make things more complicated.

(note for the future: these should have probably been two different issues 😄)
