### ISSUE TITLE
x86 Support

### ISSUE THREAD

**Issue by shmuelie** [Sergio0694/ComputeSharp#287]
### Rationale

HoloLens (1) is x86 only.

**Comment by Sergio0694** [comment]
![NoIDontThinkGIF](https://user-images.githubusercontent.com/10199417/169921356-e2fa6501-6762-4fd1-9b56-49503481afc3.gif)

**Comment by rickbrew** [comment]
Doesn't newer HoloLens support x64 ... ?

**Comment by shmuelie** [comment]
HoloLens 1 is an x86 Atom processor. HoloLens 2 is an ARM64 processor

**Comment by rickbrew** [comment]
Should work fine on HL2 then. I've got CS.D2D1 working great in Paint.NET on ARM64.

**Comment by Sergio0694** [comment]
For context, Shmueli was trying out the sample app, which uses ComputeSharp proper, not D2D1 🙂

**Comment by rickbrew** [comment]
Yeah I'd expect CS[non-.D2D1] to also work though

**Comment by Sergio0694** [comment]
Yeah in theory it _should_ work (at least, the non-dynamic version since there's no version of `dxcompiler.dll` for x86). I think I just removed the x86 target from the packaged to make things simpler, but I reckon it should be possible to add that back and build the UWP sample app from scratch for x86, and it should work, in theory 🙂
