### ISSUE TITLE
need Roslyn 4.4 in order to work

### ISSUE THREAD

**Issue by Veloctor** [Sergio0694/ComputeSharp#401]
Error prevent me from building: "The ComputeSharp source generators have been disabled on the current configuration, as they need Roslyn 4.4 in order to work. ComputeSharp requires the source generators to run in order to process shaders, so the library cannot be used without a more up to date IDE (eg. VS2022) or .NET SDK version."
My environment:
Visual Studio 2022 - v17.3.5
.Net SDK 6.0.401
.Net Runtime 6.0.9
This is the latest production environment of dotnet, but seems like version of Microsoft.Build.Tasks.CodeAnalysis.dll is 4.3.6.
Is there anything wrong with this? Do I have to use DotNet7 for this?

**Comment by Sergio0694** [comment]
This is by design, ComputeSharp is using C# 11 features and the generators are targeting Roslyn 4.4. You can use .NET 6 just fine, but you need VS 2022 17.4 or greater to use it. Until it's officially released, you can do two things for now:
- Use VS 2022 Preview (which is currently at version 17.4 Preview 2.1, which will work fine)
- Force the Roslyn version by adding this directive to your project:
```xml
<ItemGroup>
  <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="4.4.0-2.final" PrivateAssets="all" />
</ItemGroup>
```

I'll update the error message to indicate that VS 2022 version 17.4 is needed, for clarity 🙂

**Comment by Sergio0694** [comment]
Done in 59378e4cf98ddbe9333920ff7421bd2e5963d988.

**Comment by Veloctor** [comment]
thanks
