### ISSUE TITLE
Will this project support vulkan？

### ISSUE THREAD

**Issue by forestbat** [Sergio0694/ComputeSharp#41]

**Comment by Sergio0694** [comment]
Hi, thank you for your interested in ComputeSharp.
Unfortunately Vulkan support is not planned, as this library is built entirely around DX12 and the HLSL language. Parts of it could probably be reused, but the bulk of the codebase is specifically targeting just DX12, especially because they come built-in with Windows 10 and don't require any additional binaries or libraries to be installed.
