### ISSUE TITLE
Support for Hlsl.Fwidth()?

### ISSUE THREAD

**Issue by dharber** [Sergio0694/ComputeSharp#453]
I'm trying to use Hlsl.Fwidth() but I get a build error:

The shader of type ComputeSharp.SwapChain.Shaders.TestShader failed to compile due to an HLSL compiler error (Message: "The DXC compiler encountered one or more errors while trying to compile the shader: [error]: validation errors [error]: opcode 'Derivatives in CS/MS/AS' should only be used in 'Shader Model 6.6+'. Validation failed. . Make sure to only be using supported features by checking the README file in the ComputeSharp repository: https://github.com/Sergio0694/ComputeSharp. If you're sure that your C# shader code is valid, please open an issue an include a working repro and this error message.")

According to the Microsoft docs pointed to by the comments on Hlsl.Fwidth(), this should be supported in shader model 2 and above. Further, the README in the ComputeSharp repo doesn't appear to address supported features in any way, nor do the wiki pages that the README points to.

Is there a way to use the Hlsl.Fwidth intrinsic? Have I misconfigured something or simply failed to configure it properly?

Also, is there a Discord for ComputeSharp or is this the best place to ask questions?

Thanks!

**Comment by Sergio0694** [comment]
Hey there! `fwidth` is supported in pixel shaders only, as mentioned in the docs. That means that with ComputeSharp you can use it in a D2D1 pixel shader but not a DX12 compute shader. I don't really have an analyzer in place just yet to also produce warnings for this kind of scenarios, so I understand the error message might be a bit confusing. That's because all intrinsics in the `Hlsl` class are shared across the two backends, but not all work on both.

> "is there a Discord for ComputeSharp or is this the best place to ask questions?"

I don't have a dedicated Discord for ComputeSharp, but you're welcome to reach out in the [#allow-unsafe-blocks channel in the C# Discord](https://discord.com/channels/143867839282020352/312132327348240384). Other than that, for reporting issues and propose features, opening issues here on GitHub is perfectly fine 🙂
