### ISSUE TITLE
Why support only .NET Standard 2.1

### ISSUE THREAD

**Issue by mjebrahimi** [Sergio0694/ComputeSharp#46]
This project is great.
But why support only .NET Standard 2.1?
Unfortunately, .NET Framework does not support NET Standard 2.1 and it's not supposed to support, so on Windows, this project is only supported by .NET Core 3.0

Another question is, isn't it possible to use this library in Linux because of DirectX? And is there any way for using in Linux?

**Comment by Sergio0694** [comment]
Hi, thank you for your interest in ComputeSharp!
The .NET Standard 2.1 target is both to be able to use some useful APIs that are missing on 2.0 (eg. `MemoryMarshal.CreateSpan<T>(ref T, int)`, and because there are some issues when decompiling the shader code from .NET Framework >= 4.6.1 and from .NET Core 2.x. Basically, I've noticed that ILSpy returns some weird decompiled code on .NET Framework 4.6.1, which makes the rest of the library fail to work when trying to build the HLSL shader code.

Targeting .NET Standard 2.1 requires .NET Core 3.0, which solves these issues.

I might give this another shot in the future, but for now this just seemed like the easiest solution to avoid having users trying to run the library just to see it crash for no apparent reason.
