### ISSUE TITLE
INTEL HD Graphics does not show up in GraphicsDevices.EnumerateDevices() results!

### ISSUE THREAD

**Issue by Ahmed-3aly** [Sergio0694/ComputeSharp#540]
Thanks for creating this awesome library.
I was working on a compute shader and I observed a lot of latency with NVIDIA card so I turned on the IGPU (INTEL HD 4600),
However GraphicsDevices.EnumerateDevices returns only the NVIDIA GPU and the builtin WARP device but not the INTEL IGPU.
Thank you.

**Comment by Sergio0694** [comment]
That's likely because that Intel HD 4600 doesn't support the necessary DX12 feature level that ComputeSharp requires, so it just gets skipped. You could verify this by stepping into that enumerator and checking that the device is indeed found, but it then just fails the feature level check and is therefore ignored 🙂

**Comment by Ahmed-3aly** [comment]
Thanks for the elaboration.
I have another question about .CreateComputeContext() on NVIDIA.
If I try to run a kernel on the ComputeContext scope synchronously It hangs the main thread and never returns.
calling Task.Wait() on Asynchronous context causes undefined behavior.
Also running FFT kernel with ComputeSharp upload stages takes longer than CUDA's upload, execution and download times for length up to 512 * 1024 only on 1+ million samples and longer does ComputeSharp catch up to CUDA.

**Comment by Sergio0694** [comment]
> "If I try to run a kernel on the ComputeContext scope synchronously It hangs the main thread and never returns"

That's impossible to diagnose from here without having any details of your exact shader, could be all sorts of things. I'd recommend enabling the debug layer and looking at any output messages, for starters.

> "Also running FFT kernel with ComputeSharp upload stage takes longer than CUDA's upload"

That might be due to how CUDA uses a shared memory model which can help in these scenarios. It may also have to do with how you're uploading the data at each iteration.

---

I'm going to close this one, since the question about that device not showing up when itsrating has been resolved 🙂
