### ISSUE TITLE
Question: Why support only DirectX 12.1?

### ISSUE THREAD

**Issue by miyconst** [Sergio0694/ComputeSharp#64]
I am trying to experiment with different graphics cards, and figured out that my AMD RX 580 was not detected.

After some digging I found that minimum required API is DirectX 12.1, while the AMD RX 580 supports only 12.0.

I tried my test with updated minimum required API to `FeatureLevel.Level_12_0`, and it passed on AMD RX 580.

Are there some features in DirectX 12.1 which are required for this library to function?

**Comment by Sergio0694** [comment]
You're correct, DX12 should actually be enough. I'll make some tests on my end and if everything looks good I'll make this change in the next update 👍

**Comment by ElAmen** [comment]
I will be patiently waiting to help test it.

**Comment by amerkoleci** [comment]
I think even feature level 11.0 should be fine, compute shaders are supported there, it's just the minimum level you want, then you can actually trigger the max supported level by calling D3D12Device.CheckMaxSupportedFeatureLevel([ARRAY OF FEATURE LEVELS], out var maxSupportedFeatureLevel);

**Comment by Sergio0694** [comment]
Hey @amerkoleci - thanks for chiming in!
The reason why I ended up setting DX12.0 as minimum is because @aminator mentioned the fact that DX11.x doesn't have the DXIL support as mandatory, so I could end up with a GPU device that's not able to run my custom shaders, whereas with a DX12.x device that support is always guaranteed.
Of course, correct me if I'm wrong here, this is just what I gathered from my previous conversations with him about this subject. Also there should be some intrinsics that are not entirely supported on some DX11 devices, though I might be wrong about this last detail.

**Comment by Sergio0694** [comment]
I've published `ComputeSharp` version `1.3.1`, which includes a few bug fixes, minor performance improvements and support for DX12 GPUs. @miyconst and @ElAmen give it a try and let me know if that works for you! 😊

**Comment by miyconst** [comment]
Thanks @Sergio0694, now my RX 580 is detected, and in my particular case it's actually faster than GTX 1080.

**Comment by Sergio0694** [comment]
Hey @miyconst - that's awesome, thanks for the update! 🎉
