### ISSUE TITLE
Duplicate members according to IntelliSense (never effects real build)

### ISSUE THREAD

**Issue by Avid29** [Sergio0694/ComputeSharp#640]
### Reproduction Steps

This shader will occasionally raise error "Member with the same name is already declared" on the `_buffer` declaration. Sometimes it even navigates to the hlsl string when you click navigate to definition.

```cs
[GeneratedComputeShaderDescriptor]
[EmbeddedBytecode(DispatchAxis.XY)]
public partial struct DemoShader : IComputeShader
{
    private readonly ReadWriteBuffer<int> _buffer;

    public void Execute()
    {
       // This indexer will have an error saying "Cannot apply indexing an expression of type 'method group'"
        var i = _buffer[ThreadIds.X];
    }
}
```

### Expected Behavior

There should be no error.

### Actual Behavior

IntelliSense errors

### System info

This section should contain useful info such as:
- **ComputeSharp Version:** 3.0.0-alpha.6620594408
- **Visual Studio Version:** 17.7.5

### Additional context (optional)

https://github.com/Sergio0694/ComputeSharp/assets/9384045/d4725543-d83e-4787-9edf-174ef6c89694

**Comment by Sergio0694** [comment]
@333fred @cyrusnajmabadi does this seem like a Roslyn/VS bug to you? I can't repro this locally, but looking at the video I just cannot imagine a scenario where it could make sense for CTRL + click (or F12) on a member to navigate to _contents of a string literal_. I'm not even sure I understand how it's possible for any part of the compiler here to... Seemingly incorrectly parse some contents of a raw multiline string literal as if they were actual code? Because eg. here CTRL + click on that field jumps to a field declared in the transpired HLSL, which is just a line in a string literal 🤔

**Comment by Avid29** [comment]
I've modified the sample code to include the issue where indexers might say `Cannot apply indexing an expression of type 'method group'`. I believe this is part of the same issue, and it might suggest that somewhere a 'method group' is being defined that conflicts with these buffers?

**Comment by Sergio0694** [comment]
Closing this as out of scope, as this seems to just be some issue with either IntelliSense, or possibly some other extension. I'd recommend creating a Visual Studio feedback item using the option to record a repro video, which will include all necessary logs there. They can help investigate it from here. It's impossible otherwise without logs and traces to learn more 🙂
