### ISSUE TITLE
Use ComputeSharp to apply existing compiled HLSL shaders to images?

### ISSUE THREAD

**Issue by brischt** [Sergio0694/ComputeSharp#663]
Hi,

first of all, this looks like a great library - Kudos!

I might be completely barking up the wrong tree - I apologize if so.
My question is: I have a WPF application which uses custom compiled HLSL shaders to apply effects on images. This works quite well; however, my app is supposed to process a lot of image files with those effects applied in batch. This is quite slow as the usual approach using a RenderTargetBitmap is executed on the CPU. So, could I somehow use ComputeSharp to apply the already compiled shaders to ImageSource objects on the GPU even without displaying the images?

Thank you for your help!

**Comment by rickbrew** [comment]
You would need to port your shaders over to ComputeSharp and Direct2D, but it should work. One thing to watch out for is that different GPUs, and even different driver versions for the same GPU, can produce slightly different results because Direct3D allows some leniency versus strict IEEE-754 rules https://learn.microsoft.com/en-us/windows/win32/direct3d11/floating-point-rules 

So if you need strictly consistent output you'd still want to use software rendering with WARP. You might also be able to use `[D2DCompilerOptions(D2D1CompileOptions.Default | D2D1CompileOptions.IeeeStrictness)]` on your shaders, it might improve the consistency across GPUs and driver versions, but I don't know if it requires actual IEEE-754 conformance or just "better" conformance (see also `D3DCOMPILE_IEEE_STRICTNESS`).

**Comment by brischt** [comment]
Thanks Rick, I'll look into it!
